# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83b5c1d5132e05e8cdeea26bd5ebd0e06f9d2a7b983359ef13c5c7a26ffe88a6936f71d41b8e9ae9aaa42b05a2fe477f450a2dd8a08c03513c916fdf703f36a3

test:
  secret_key_base: 042c1accc96f8955010f39b5937b4f9043d60e998caa5d7d12c889eeabbb58a512caff6cbb6b97919560b6bb4f694524b4c1b9382ab9b2d97eec36d6be618da7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
